{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: loft-config
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
data:
  config: {{ toYaml .Values.config | b64enc }}
{{- end }}